### ISSUE TITLE
Error message with SWSC-EN

### ISSUE THREAD

**Issue by lcgraber** [Tagliacollo/PFinderUCE-SWSC-EN#22]
Hi,

I am trying to run SWSC-EN with .nexus output from phyluce. I keep getting this same error message:

analysing %s /Users/admin/Documents/Phyluce/mafft-nexus-edge-trimmed-clean-75p-nex-new.nexus
Wed Feb 23 09:13:25 2022
Sitewise metrics analysis
Traceback (most recent call last):
  File "/Users/admin/Downloads/PFinderUCE-SWSC-EN-master/py_script/SWSCEN.py", line 25, in <module>
    process_dataset_metrics(dataset_path, ['entropy'], minimum_window_size = 50, outfilename = '%s.csv' % (name))
  File "/Users/admin/Downloads/PFinderUCE-SWSC-EN-master/py_script/functions_metrics.py", line 37, in process_dataset_metrics
    dat.read(dataset_path)
  File "/Users/admin/miniconda3/lib/python3.9/site-packages/Bio/Nexus/Nexus.py", line 718, in read
    self._parse_nexus_block(title, contents)
  File "/Users/admin/miniconda3/lib/python3.9/site-packages/Bio/Nexus/Nexus.py", line 759, in _parse_nexus_block
    getattr(self, "_" + line.command)(line.options)
  File "/Users/admin/miniconda3/lib/python3.9/site-packages/Bio/Nexus/Nexus.py", line 1275, in _charpartition
    subname, subindices = self._get_indices(
  File "/Users/admin/miniconda3/lib/python3.9/site-packages/Bio/Nexus/Nexus.py", line 1295, in _get_indices
    name = self._name_n_vector(opts, separator=separator)
  File "/Users/admin/miniconda3/lib/python3.9/site-packages/Bio/Nexus/Nexus.py", line 1320, in _name_n_vector
    raise NexusError("Formatting error in line: %s " % rest)
Bio.Nexus.Nexus.NexusError: Formatting error in line:  uce-10.nexus: 1-1236 

Do you have any idea what might be going wrong? I can send my alignment file but it is very large (559 MB).

Thank you!
Leland

**Comment by roblanf** [comment]
Hi Leland,

It looks like BioPython can't read your Nexus file. This could be for a few different reasons. Can you post the first and last few lines here?

Otherwise, if you compress it with `xz -e` you can probably get pretty good compression and then send it through. Either @Tagliacollo or I can take a look.

Rob

**Comment by Tagliacollo** [comment]
Dear @lcgraber,

Please let me know if you could fix the issue.

Victor

**Comment by lcgraber** [comment]
Hi! I apologize for not replying sooner--my .nexus output from phyluce lacked the "[loci]" specified right before the charsets, and my uce loci had hyphens in their names, which I replaced with underscores like in the sample input. One or both of those changes made my alignment run correctly!

So, my file before:
begin sets;
CHARSET uce-10 = 1-689;
CHARSET uce-100 = 690-1255;
CHARSET uce-10001 = 1256-1557;

and after:
begin sets;
[loci]
CHARSET uce_10 = 1-689;
CHARSET uce_100 = 690-1255;
CHARSET uce_10001 = 1256-1557;

The output looks great! Thanks for making such a helpful program.

All the best,
Leland

**Comment by roblanf** [comment]
@lcgraber, thanks so much for working this out. Hopefully this record of the issue will help others avoid this problem too. 

Rob
